Update im-build-npm-package.yml
im-practices/.github pull request #145
Opened 2022-05-17 22:51 UTC by mike-schenk

2022-05-18 19:38 UTC, hpractv submitted a review, later dismissed
👍🏽

2022-05-19 12:10 UTC, JosephDSchwartz requested changes

2022-05-19 12:10 UTC, JosephDSchwartz commented on workflow-templates/im-build-npm-package.yml
> +      - name: Cleanup start-project pre-release packages
We should have them add their project name, or make the step generically named like this:
```suggestion
      - name: Cleanup pre-release packages
```

2022-05-19 18:56 UTC, JosephDSchwartz approved these changes

2022-05-19 18:57 UTC, merged