create-github-deployment
im-practices/.github pull request #246
Opened 2024-02-02 15:55 UTC by hpractv

Replaced update-deployment-board with create-github-deployment

2024-02-02 19:00 UTC, danielle-casella-adams requested changes

2024-02-02 19:01 UTC, danielle-casella-adams commented
I forgot to add the comment to the review.  In most of the workflows the last job is called `update-deployment-board-and-send-teams-notification`.  Should that be updated?  At a minimum I think we take the `board` part out.

2024-02-05 17:27 UTC, hpractv commented
> I forgot to add the comment to the review. In most of the workflows the last job is called `update-deployment-board-and-send-teams-notification`. Should that be updated? At a minimum I think we take the `board` part out.

I'll change it to `update-github-deployments-and-send-teams-notification`.

2024-02-06 16:58 UTC, danielle-casella-adams approved these changes

2024-02-06 17:21 UTC, merged